### ISSUE TITLE
Add external links to Chapter Profile page

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#11]
Chapter profile pages display the Chapter title and description. We would like to add a bit more information to Chapter profiles, such as:

links to
- social media
- chapter website

## Task
- [ ] discuss what fields to add to the Chapter model (i.e. field names and types)
- [ ] add desired field(s) to Chapter model
- [ ] make migrations
- [ ] render field data in the Chapter profile template

## Possible resource(s)
This might be a good task for the Wagtail StreamField, in that it would allow zero or more (up to perhaps three) links to be added to the Chapter. StreamFields support [limiting the number of sub-blocks](https://docs.wagtail.io/en/stable/topics/streamfield.html#limiting-block-counts).

**Comment by brylie** [comment]
The idea for "chapters" is basically groups of people that share a geographic location. E.g. people from the same country or city. We could start more generic and just model `groups` and then later create a `chapter` sub-type that inherits from `group`.

**Comment by brylie** [comment]
Yep. That way people can form groups around various interests, topics, etc.

We would use a [many-to-many relationship](https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_many/) for group membership.

**Comment by Upasanadhameliya** [comment]
@brylie Now that one pr has been merged, would you like to add some more features to chapters? Are there any tasks remaining? If so, feel free to discuss further about it.

**Comment by brylie** [comment]
We can still add a "website" field to the `Chapter` model, as per #11

Similarly, issue #12 might be interesting.

**Comment by Upasanadhameliya** [comment]
I will open a draft pr shortly in order to add the social media links
