### ISSUE TITLE
Display Chapters on ChapterIndexPage

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#16]
We currently have two models, `Chapter` and `ChapterIndexPage`. The `ChapterIndexPage` is intended to help people find chapters of interest.

## Task
- [ ] return a Queryset of Chapters by [shadowing the `get_context` method](https://docs.wagtail.io/en/stable/topics/pages.html#customising-template-context) of the [ChapterIndexPage model](https://github.com/brylie/wagtail-social-network/blob/b3fffb94a25730acef43569a47c3e9b2ad73d0dd/project/chapters/models.py#L9)
- [ ] use the `chapters` context variable to add a list of Chapters to the Chapter Index Page
- [ ] ` regroup` the Chapters by `region`
- [ ] regions should be headings
- [ ] Chapters should link to the chapter page
- [ ] use Bootstrap classes to organize the page cleanly
    - use your creativity and best judgment
    - consider submitting a sketch of your idea for discussion prior to finalizing the design 

## Resources

- [Bootstrap 5 introduction](https://getbootstrap.com/docs/5.0/getting-started/introduction/)
- Django [regroup](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#regroup) template tag

**Comment by brylie** [comment]
@sp35, how are you doing? I mentioned that I would ping you from this project. Would you be interested in working on a Django-related task such as this one?

**Comment by sp35** [comment]
Looks doable, I'll see it on the weekend.

**Comment by brylie** [comment]
Cool, thanks! FWIW, this is pretty much a Django templating task. The part that might be unfamiliar is how to populate the Wagtail Page context using `get_context,` so I added links to the documentation in the issue checklist.
