### ISSUE TITLE
Define custom user model

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#3]
It is recommended to create a custom user model early in a project lifespan, to allow the model to be modified with changes over time.

Define an initial custom user model, inheriting from `AbstractUser`. Keep all of the same fields, but make the `first_name` and `last_name` fields optional. If needed, configure the Wagtail Edit User Form with the updated fields, although it may just work without any configuration.

Docs: https://docs.wagtail.io/en/stable/advanced_topics/customisation/custom_user_models.html

## Task
Complete each of the following steps. If possible, commit changes made during each successful step. Each step is accompanied by the corresponding documentation.

### [Using a custom user model when starting a project](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project)
- [ ] define a custom `User` model in `accounts/models.py` and run `python manage.py makemigrations`
  - make sure to inherit from `AbstractUser` so the data model stays the same 
- [ ] register the custom `User` model along with `contrib.auth.admin.UserAdmin` in `admin.py`
- [ ] configure Django to use the new user model by adding `AUTH_USER_MODEL = 'accounts.User'` to `/core/settings/base.py`

**Comment by Upasanadhameliya** [comment]
Claim Issue

**Comment by Upasanadhameliya** [comment]
@brylie I will create the usermodel in `accounts` app. Is that okay or should I create it in a different app?

**Comment by brylie** [comment]
@Upasanadhameliya thank you! Yes, the `accounts` app is the perfect place for the custom user model.

**Comment by brylie** [comment]
@Upasanadhameliya feel free to @ mention me at any time. I am on GitHub throughout the day for work and will try to respond promptly.

**Comment by Upasanadhameliya** [comment]
@brylie when I try to migrate the User model it gives the following error:
```
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\management\commands\migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\db\migrations\loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency accounts.0001_initial on database 'default'.
```
I tried searching for a solution online but it involves some database modification. If you have an idea about it please tell.
Thanks

**Comment by brylie** [comment]
First, delete the file `db.sqlite`. Then run `python manage.py makemigrations`. 

The issue may be that the existing database already has migrations applied that created the initial `User` model based on the Django internal User model.

**Comment by brylie** [comment]
Hei @Upasanadhameliya, just checking in. Will you be opening a pull request for review soon? It sounds like you already have code that is ready to review. A pull request would allow me to review the code early as well as contribute to overcoming any obstacles.

**Comment by Upasanadhameliya** [comment]
@brylie I am trying to add custom forms.. I did change the settings file as its given.. I tried it with both 'users.forms.CustomUserEditForm' and 'accounts.forms.CustomUserEditForm' but it gives the following error:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/users/1/

Django Version: 3.2.4
Python Version: 3.8.10
Installed Applications:
['accounts',
 'chapters',
 'home',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.modeladmin',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\utils\loading.py", line 9, in get_custom_form
    return import_string(getattr(settings, form_setting))
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
    <source code not available>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    <source code not available>
  File "S:\Sandy\Documents\College\Practice\Python\Task\wagtail-social-network\project\accounts\forms.py", line 4, in <module>
    from wagtail.users.forms import UserEditForm, UserCreationForms

During handling of the above exception (cannot import name 'UserCreationForms' from 'wagtail.users.forms' (C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\users\forms.py)), another exception occurred:
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\admin\urls\__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\admin\auth.py", line 60, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\users\views\users.py", line 180, in edit
    form = get_user_edit_form()(instance=user, editing_self=editing_self)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\users\views\users.py", line 44, in get_user_edit_form
    return get_custom_form(form_setting)
  File "C:\Users\Upasana\anaconda3\envs\wagtail38\lib\site-packages\wagtail\utils\loading.py", line 11, in get_custom_form
    raise ImproperlyConfigured(

Exception Type: ImproperlyConfigured at /admin/users/1/
Exception Value: WAGTAIL_USER_EDIT_FORM refers to a form 'accounts.forms.CustomUserEditForm' that is not available
```

**Comment by brylie** [comment]
@Upasanadhameliya  would you open a pull request with your current changes? I'll try and run the code as it stands and see if there is a simple fix :smiley:

**Comment by brylie** [comment]
On second thought, you should only need to

1. define a custom user model
2. use the existing Django accounts URLs
3. define minimal templates for the accounts class-based views

I will update this comment with links to the specific documentation.

**Comment by brylie** [comment]
@Upasanadhameliya, how are you doing? Is there any other blocker to this issue? I hope the steps I outlined in the issue description are helpful so that you don't need to write much code or have too many difficulties.
