### ISSUE TITLE
Add "online hangout/meeting" feature

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#45]
We would like to foster connections between community members who may be in different locations around the world.To support this goal, we can add a `Hangout` feature (or something similar like `Meeting`.)

## Task

- [ ] create a new app for hangouts/meetings
- [ ] create a `Hangout` or `Meeting` model (or something similar)
   - [ ] `title` field
   - [ ] `description` RichText field
   - [ ] `topics` keword select field, e.g. with `django-taggit`
   - [ ] `URL` field (optional) to link to external meeting
- [ ] add templates for creating and displaying hangout/meetings
- [ ] in the template, render the meeting title, description,and keywords
- [ ] keywords should link to a keyword page listing related meeting/hangouts
- [ ] if possible, we can render a Jitsi Meet room with an ID based on the database ID

**Comment by Upasanadhameliya** [comment]
@brylie I would like to work on this issue, please assign me the same! :octocat:

**Comment by brylie** [comment]
Very cool! There is some latitude with how you think we can achieve this issue. For a reference point, consider the Codebuddies.org website hangout feature.

**Comment by Upasanadhameliya** [comment]
@brylie do we need other fields in the "Hangouts" model, such as `time` and/or `duration`, and the type of hangout like `silent`, `teaching` ,etc. ?

**Comment by brylie** [comment]
Adding `start_time` and `end_time` fields could be helpful in scheduling hangouts in advance. However, I'm not sure what would be the ideal UX, so let's use DateTime fields for now and look at a user-friendly DateTime widget.

Otherwise, let's keep the Hangout model as generic and straightforward as possible. The `keywords` field is already quite flexible.

We can consider a `members` property later if we add an "RSVP" feature to the scheduled Hangout.

**Comment by Upasanadhameliya** [comment]
@brylie is it possible to render the Jitsi meet room using `python` itself? Or would I need to integrate it from the frontend using `javascript`?

**Comment by brylie** [comment]
It should only take a few lines of JavaScript to render a Jitsi meeting room in the Django template:

https://jitsi.org/api/

We can use the Hangout UUID for the Jitsi meeting name or something unique and hard to guess.
